export declare function unifyEvent(e: any): any;
export declare function debounce(func: Function, timeout?: number): (...args: any[]) => void;
export declare function isMobile(): boolean;
export declare function isIOS(): boolean;
export declare function isIPad(): boolean;
export declare function isFullscreen(): boolean;
export declare function isFirefox(): boolean;
export declare const isSafari: () => boolean;
export declare function isRTL(): boolean;
export declare function isLandscape(): boolean;
export declare function isPortrait(): boolean;
export declare const isAndroid: () => boolean;
export declare const isAndroidTablet: () => boolean;
